apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: bucketlist
  name: bucketlist
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: bucketlist
  type: LoadBalancer
status:
  loadBalancer: {}
